# Generated by Django 5.2 on 2026-02-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpisy', '0005_alter_entry_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='temp', unique=True),
            preserve_default=False,
        ),
    ]
