# Generated by Django 5.2 on 2026-02-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpisy', '0006_alter_category_options_alter_entry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
