# Generated by Django 5.2 on 2026-02-08 01:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpisy', '0007_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
        migrations.AddField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default=None, upload_to='entries/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='wpisy.entry'),
        ),
    ]
